#==========================================================================
# Description: Build Armbian
# Copyright (C) 2023 https://github.com/windbell-project/msm8916-armbian
#==========================================================================

name: Rebuild armbian

on:
  workflow_dispatch:
    inputs:
      armbian_board:
        description: "选择设备"
        required: true
        default: "ufi001c"
        type: choice
        options:
          - ufi001c
          - ufi003

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 安装依赖
        run: |
          sudo apt update -y
          sudo apt-get install -y zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full img2simg qemu-user-static
          sudo apt clean
      - name: 下载源码
        run: |
          git clone https://github.com/windbell-project/msm8916-armbian
      - name: 下载镜像
        run: |
          pushd msm8916-armbian
          ./download
          popd
      - name: 打包 Armbian
        id: repack
        run: |
          pushd msm8916-armbian
          sudo mkdir armbian
          sudo mkdir armbian-msm8916
          sudo mkdir temp
          sudo dd if=/dev/zero of=temp.img bs=1M count=1536
          sudo dd if=/dev/zero of=armbian-msm8916.img bs=1M count=1234
          sudo mkfs.btrfs armbian-msm8916.img
          sudo mkfs.btrfs temp.img
          sudo mount -o compress=zstd:15 temp.img temp
          sudo mount -o compress=zstd:15 armbian-msm8916.img armbian-msm8916
          sudo losetup -P /dev/loop404 armbian.img
          sudo mount /dev/loop404p1 armbian
          sudo cp -rfp armbian/* temp
          sudo cp common-file/* temp/tmp
          sudo cp kernel/*.deb temp/tmp
          sudo cp modem/firmware-${{ inputs.armbian_board }}.deb temp/tmp
          sudo mount --bind /proc temp/proc
          sudo mount --bind /dev temp/dev
          sudo mount --bind /dev/pts temp/dev/pts
          sudo mount --bind /sys temp/sys
          sudo chroot temp /tmp/chroot.sh
          sudo rm temp/tmp/*
          sudo umount temp/proc
          sudo umount temp/dev/pts
          sudo umount temp/dev
          sudo umount temp/sys
          sudo cp -rfp temp/* armbian-msm8916
          sudo umount temp
          sudo umount armbian-msm8916
          sudo umount armbian
          sudo losetup -d /dev/loop404
          sudo img2simg armbian-msm8916.img rootfs.img
          sudo rm temp.img
          sudo rm -rf armbian
          sudo rm -rf armbian-msm8916
          sudo rm -rf temp
          popd
          echo "build_tag=Armbian_noble_save_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}
      - name: 上传 Armbian 镜像至 Release
        uses: ncipollo/release-action@main
        with:
          artifacts: "msm8916-armbian/rootfs.img,msm8916-armbian/kernel/boot.img"
          name: ${{ steps.repack.outputs.build_tag }}
          tag: ${{ steps.repack.outputs.build_tag }}
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### 以下是 Armbian OS 镜像
            - 本次固件基带为${{ inputs.armbian_board }}
            - 系统信息：
            - 默认用户名：root
            - 默认密码：1234
            - 全局配置命令：armbian-config
            - WiFi名称：4G-UFI
            - WiFi密码：12345678
            - 如遇无法开机的情况请使用未超频内核boot-no-overclock.img
